import os

base_dir = "/media/hp-ml10/ర్ణProjects/EwasteKochi.com"
base_dir = "/media/hp-ml10/Projects/EwasteKochi.com"

directories = ["industries", "compliance", "blog"]
for d in directories:
    os.makedirs(os.path.join(base_dir, d), exist_ok=True)

files_to_scaffold = [
    # Master Pillar 1 Subpages
    "iphone-buyback-kochi.html",
    "samsung-buyback-kochi.html",
    "macbook-buyback-kochi.html",
    "tablet-buyback-kochi.html",
    "best-price-used-iphone-kochi-2026.html",
    "olx-alternative-kochi.html",

    # Master Pillar 2 Subpages
    "data-wiping-vs-shredding.html",
    "hard-drive-shredding-kochi.html",
    "certificate-of-destruction.html",

    # Master Pillar 3 Subpages
    "how-ewaste-is-recycled.html",
    "environmental-impact-ewaste.html",

    # Locations
    "thrippunithura-ewaste.html",
    "edappally-ewaste.html",
    "vyttila-ewaste.html",
    "ernakulam-ewaste.html",
    "aluva-ewaste.html",
    "angamaly-ewaste.html",

    # Industries
    "industries/it-companies-kochi.html",
    "industries/banks-data-destruction.html",
    "industries/hospitals-ewaste.html",
    "industries/government-itad.html",
    "industries/startups-itad.html",

    # Compliance
    "compliance/nist-800-88-explained.html",
    "compliance/dpdp-act-2023-ewaste-penalties.html",
    "compliance/chain-of-custody-process.html",

    # Blog Categories
    "blog/how-to-sell-old-phone-without-olx-risks.html",
    "blog/is-formatting-enough-data-delete.html",
    "blog/hard-disk-data-recovery-risk.html",
    "blog/dpdp-act-penalties-explained.html",
    
    # Trust
    "reviews.html",
    "case-studies.html"
]

template = """<!DOCTYPE html>
<html lang="en-IN" dir="ltr">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<!-- Placeholder title generated by SEO scaffolding engine -->
<title>{title} | EWaste Kochi</title>
<link rel="stylesheet" href="{depth}assets/css/style.css">
</head>
<body style="background:var(--ow);">

<header class="header" id="nav">
  <div class="wrap nav-container">
    <a href="{depth}index.html" class="logo">
      <div class="logo-icon">♻️</div>EWaste<em>Kochi</em>
    </a>
  </div>
</header>

<div class="wrap" style="padding:150px 0;text-align:center;">
    <div class="ey">SEO Scaffolding Module</div>
    <h1 style="margin:20px 0;">{title}</h1>
    <p style="color:var(--sub);margin-bottom:30px;">This module has been allocated in the 2026 enterprise architecture and is awaiting full content deployment.</p>
    <a href="{depth}index.html" class="btn btn-primary" style="margin-top:20px;">Return Home</a>
</div>
</body>
</html>"""

for file_path in files_to_scaffold:
    full_path = os.path.join(base_dir, file_path)
    
    # Calculate relative depth to root for assets
    depth = "../" * file_path.count("/")
    
    # Format a clean title from the filename
    title = file_path.split("/")[-1].replace("-", " ").replace(".html", "").title()
    
    # Create sub-directories if needed (for nested structure)
    os.makedirs(os.path.dirname(full_path), exist_ok=True)
    
    # Only write if the file doesn't already exist or is empty
    if not os.path.exists(full_path) or os.path.getsize(full_path) == 0:
        with open(full_path, "w") as f:
            f.write(template.format(title=title, depth=depth))

print(f"Scaffolding completed: {len(files_to_scaffold)} silo structure elements generated successfully.")
